### ISSUE TITLE
BUGFIX: Crafter Placeholder is missing (mistranslated to mcfunction)

### ISSUE THREAD

**Issue by aviad1b** [Stevertus/objd_crafting#2]
Hi, I have the following code in objd:
```
CraftingTable(
  name: "crafter",
  displayName: TextComponent("Crafter"),
  useBarrel: true,
  guiModel: Item(Items.apple),
  placeholder: Item(Items.blue_stained_glass_pane),
  recipes: [
    Recipe({
      5: Item(Blocks.stone),
      8: Item(Items.coal)
    },
    Item(Blocks.furnace, count: 2))
  ]
)
```

However, the placeholders does not appear in the crafter.
When I check out the mcfunction I see the following:
`execute unless block ~ ~ ~ minecraft:barrel unless block ~ ~ ~ minecraft:barrel run data modify entity @s HandItems[0] set from block ~ ~ ~ Items[{Slot:0b}]`
It appears that when translating to mcfunction, objd forgets to add the block condition (it simply writes `unless block ~ ~ ~ minecraft:barrel` without giving the condition NBT).

EDIT:
It appears that block NBT in execute (if|unless) block is not supported.
A different method could be to use the `data` keyword instead:
```unles block ~ ~ ~ barrel{Items:[{Slot:0b, id: "minecraft:armor_stand", count: 1b, tag:{CustomModelData:0,crafterPlaceholder:1}}]}```
becomes
```unless data block ~ ~ ~ {Items:[{Slot:0b, id: "minecraft:armor_stand", count: 1b, tag:{CustomModelData:0,crafterPlaceholder:1}}]}```

**Comment by Stevertus** [comment]
Thanks for reporting! This was actually a bug with objD in general where nbt was not accepted as String,
Should be fixed with v0.2 and objD 0.4.1 now
